LIB_UNAME_PRELOAD32 = libuname_preload_32.so
LIB_UNAME_PRELOAD64 = libuname_preload_64.so
CC=gcc
CFLAGS += -g -D _GNU_SOURCE
lib%_32.so: %.c
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

lib%_64.so: %.c
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(LIB_UNAME_PRELOAD32): LDFLAGS += -shared -fpic -ldl -m32
$(LIB_UNAME_PRELOAD64): LDFLAGS += -shared -fpic -ldl -m64
all: $(LIB_UNAME_PRELOAD32) $(LIB_UNAME_PRELOAD64)

clean:
	@rm -f $(LIB_UNAME_PRELOAD32) $(LIB_UNAME_PRELOAD64)

